export interface Movie {
  id: number;
  title: string;
  year: number;
  rating: number;
  votes: string;
  genres: string[];
  runtime: string;
  overview: string;
  tagline?: string;
  poster: string;
  backdrop: string;
  certification?: string;
  language?: string;
  director?: string;
  cast?: string[];
  status?: string;
  revenue?: string;
  budget?: string;
  popularity?: number;
  trailer?: string;
  provider?: string;
}

export interface TVShow {
  id: number;
  title: string;
  year: number;
  rating: number;
  genres: string[];
  overview: string;
  poster: string;
  backdrop: string;
  network?: string;
  seasons?: number;
}

export interface Actor {
  id: number;
  name: string;
  role: string;
  photo: string;
  popularity: number;
  knownFor?: string;
}

export const GENRES = [
  'All', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime',
  'Documentary', 'Drama', 'Fantasy', 'Horror', 'Musical',
  'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'Biography'
];

export const TRENDING_MOVIES: Movie[] = [
  {
    id: 603692,
    title: 'John Wick: Chapter 4',
    year: 2023,
    rating: 7.8,
    votes: '4.2K',
    genres: ['Action', 'Thriller', 'Crime'],
    runtime: '2h 49m',
    overview: 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.',
    tagline: 'No way back, one way out.',
    poster: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    backdrop: '/fgsHxz21B27hOOqQBiw9L6yWcM7.jpg',
    certification: 'R',
    language: 'English',
    director: 'Chad Stahelski',
    cast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård', 'Laurence Fishburne'],
    popularity: 98.4,
    provider: 'Prime Video',
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    year: 2023,
    rating: 8.3,
    votes: '6.8K',
    genres: ['Biography', 'Drama', 'History'],
    runtime: '3h 0m',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II.',
    tagline: 'The world forever changes.',
    poster: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    certification: 'R',
    language: 'English',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    popularity: 96.1,
    provider: 'Peacock',
  },
  {
    id: 792307,
    title: 'Poor Things',
    year: 2023,
    rating: 7.8,
    votes: '2.1K',
    genres: ['Comedy', 'Romance', 'Sci-Fi'],
    runtime: '2h 21m',
    overview: 'The incredible tale of Bella Baxter, a young woman brought back to life by an eccentric surgeon.',
    tagline: 'She is her own creation.',
    poster: '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
    backdrop: '/qW4crfED8mpNDadSmMdi7ZDzhNv.jpg',
    certification: 'R',
    language: 'English',
    director: 'Yorgos Lanthimos',
    cast: ['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe', 'Ramy Youssef'],
    popularity: 87.5,
    provider: 'Hulu',
  },
  {
    id: 533535,
    title: 'Deadpool & Wolverine',
    year: 2024,
    rating: 7.7,
    votes: '5.3K',
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    runtime: '2h 8m',
    overview: 'A listless Wade Wilson toils away in civilian life. His days as Deadpool behind him, until he faces a threat that could destroy his world.',
    tagline: 'Come together.',
    poster: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdrop: '/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
    certification: 'R',
    language: 'English',
    director: 'Shawn Levy',
    cast: ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Morena Baccarin'],
    popularity: 91.2,
    provider: 'Disney+',
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    year: 2024,
    rating: 8.2,
    votes: '4.9K',
    genres: ['Sci-Fi', 'Adventure'],
    runtime: '2h 46m',
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    tagline: 'Long live the fighters.',
    poster: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    certification: 'PG-13',
    language: 'English',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
    popularity: 98.4,
    provider: 'Max',
  },
  {
    id: 653346,
    title: 'Kingdom of the Planet of the Apes',
    year: 2024,
    rating: 7.0,
    votes: '1.8K',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    runtime: '2h 25m',
    overview: 'Several generations in the future following Caesar\'s reign, apes are living harmoniously while humans have been reduced to living in the shadows.',
    tagline: 'No one can stop the reign.',
    poster: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    backdrop: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
    certification: 'PG-13',
    language: 'English',
    director: 'Wes Ball',
    cast: ['Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon'],
    popularity: 78.9,
    provider: 'Hulu',
  },
  {
    id: 748783,
    title: 'The Garfield Movie',
    year: 2024,
    rating: 7.2,
    votes: '856',
    genres: ['Animation', 'Comedy', 'Family'],
    runtime: '1h 41m',
    overview: 'Garfield, the world-famous indoor cat who hates Mondays and loves lasagna, is about to have a wild outdoor adventure!',
    tagline: 'Hungry for adventure.',
    poster: '/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg',
    backdrop: '/xRd1eJIDe7JHO5u4gtEYwGn5wtf.jpg',
    certification: 'PG',
    language: 'English',
    director: 'Mark Dindal',
    cast: ['Chris Pratt', 'Samuel L. Jackson', 'Hannah Waddingham', 'Ving Rhames'],
    popularity: 74.3,
    provider: 'Netflix',
  },
  {
    id: 573435,
    title: 'Bad Boys: Ride or Die',
    year: 2024,
    rating: 7.6,
    votes: '1.9K',
    genres: ['Action', 'Crime', 'Thriller'],
    runtime: '1h 55m',
    overview: 'When their late police captain gets linked to drug cartels, wisecracking Miami cops Mike Lowrey and Marcus Burnett must clear his name.',
    tagline: 'Miami\'s finest are now its most wanted.',
    poster: '/oGythE98MYleE6mZlGs5oBGkux1.jpg',
    backdrop: '/ga4OLIa5Vfx82fUUZBaBLihNTfG.jpg',
    certification: 'R',
    language: 'English',
    director: 'Adil El Arbi',
    cast: ['Will Smith', 'Martin Lawrence', 'Vanessa Hudgens', 'Alexander Ludwig'],
    popularity: 88.1,
    provider: 'Netflix',
  },
];

export const FEATURED_MOVIE: Movie = {
  id: 693134,
  title: 'Dune: Part Two',
  year: 2024,
  rating: 8.2,
  votes: '4.9K',
  genres: ['Sci-Fi', 'Adventure'],
  runtime: '2h 46m',
  overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future only he can foresee.',
  tagline: 'Long live the fighters.',
  poster: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
  backdrop: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
  certification: 'PG-13',
  language: 'English',
  director: 'Denis Villeneuve',
  cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
  popularity: 98.4,
  provider: 'Max',
};

export const HERO_MOVIE: Movie = {
  id: 693134,
  title: 'Dune: Part Two',
  year: 2024,
  rating: 8.2,
  votes: '4.9K',
  genres: ['Sci-Fi', 'Adventure'],
  runtime: '2h 46m',
  overview: 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe.',
  tagline: 'Long live the fighters.',
  poster: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
  backdrop: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
  certification: 'PG-13',
  language: 'English',
  director: 'Denis Villeneuve',
  cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Josh Brolin'],
  popularity: 98.4,
  provider: 'Max',
};

export const TOP_RATED_MOVIES: Movie[] = [
  {
    id: 278,
    title: 'The Shawshank Redemption',
    year: 1994,
    rating: 8.7,
    votes: '28K',
    genres: ['Drama', 'Crime'],
    runtime: '2h 22m',
    overview: 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    poster: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    backdrop: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    certification: 'R',
    director: 'Frank Darabont',
  },
  {
    id: 238,
    title: 'The Godfather',
    year: 1972,
    rating: 8.7,
    votes: '20K',
    genres: ['Crime', 'Drama'],
    runtime: '2h 55m',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.',
    poster: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    certification: 'R',
    director: 'Francis Ford Coppola',
  },
  {
    id: 240,
    title: 'The Godfather Part II',
    year: 1974,
    rating: 8.6,
    votes: '13K',
    genres: ['Crime', 'Drama'],
    runtime: '3h 22m',
    overview: 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York.',
    poster: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
    backdrop: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
    certification: 'R',
    director: 'Francis Ford Coppola',
  },
  {
    id: 424,
    title: 'Schindler\'s List',
    year: 1993,
    rating: 8.6,
    votes: '16K',
    genres: ['Biography', 'Drama', 'History'],
    runtime: '3h 15m',
    overview: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives during the Holocaust.',
    poster: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    backdrop: '/aLvH7qfXolk0mHQ0i8nQ8GPGear.jpg',
    certification: 'R',
    director: 'Steven Spielberg',
  },
  {
    id: 19404,
    title: 'Dilwale Dulhania Le Jayenge',
    year: 1995,
    rating: 8.6,
    votes: '4.5K',
    genres: ['Comedy', 'Drama', 'Romance'],
    runtime: '3h 1m',
    overview: 'Raj and Simran meet on a trip across Europe and fall in love. However, Simran is already promised to another man.',
    poster: '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
    backdrop: '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
    certification: 'PG-13',
    director: 'Aditya Chopra',
  },
  {
    id: 155,
    title: 'The Dark Knight',
    year: 2008,
    rating: 8.5,
    votes: '34K',
    genres: ['Action', 'Crime', 'Drama'],
    runtime: '2h 32m',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.',
    poster: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    certification: 'PG-13',
    director: 'Christopher Nolan',
  },
];

export const UPCOMING_MOVIES: Movie[] = [
  {
    id: 558449,
    title: 'Gladiator II',
    year: 2024,
    rating: 6.8,
    votes: '1.5K',
    genres: ['Action', 'Adventure', 'Drama'],
    runtime: '2h 28m',
    overview: 'Years after witnessing the death of Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered.',
    poster: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdrop: '/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg',
    director: 'Ridley Scott',
  },
  {
    id: 823464,
    title: 'Godzilla x Kong: The New Empire',
    year: 2024,
    rating: 7.1,
    votes: '2.6K',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    runtime: '1h 55m',
    overview: 'The almighty Kong and the fearsome Godzilla unite against a colossal undiscovered threat hidden within our world.',
    poster: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    backdrop: '/bKpg3DT8i2Qq3qGMNRBe1pDYOzw.jpg',
    director: 'Adam Wingard',
  },
  {
    id: 519182,
    title: 'Despicable Me 4',
    year: 2024,
    rating: 7.2,
    votes: '1.4K',
    genres: ['Animation', 'Comedy', 'Family'],
    runtime: '1h 34m',
    overview: 'Gru and Lucy and their girls welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad.',
    poster: '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
    backdrop: '/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg',
    director: 'Chris Renaud',
  },
  {
    id: 1184918,
    title: 'The Wild Robot',
    year: 2024,
    rating: 8.5,
    votes: '3.2K',
    genres: ['Animation', 'Sci-Fi', 'Family'],
    runtime: '1h 42m',
    overview: 'After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island.',
    poster: '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    backdrop: '/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg',
    director: 'Chris Sanders',
  },
];

export const TV_SHOWS: TVShow[] = [
  {
    id: 94997,
    title: 'House of the Dragon',
    year: 2022,
    rating: 8.4,
    genres: ['Action', 'Drama', 'Fantasy'],
    overview: 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights.',
    poster: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
    backdrop: '/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
    network: 'HBO',
    seasons: 2,
  },
  {
    id: 100088,
    title: 'The Last of Us',
    year: 2023,
    rating: 8.7,
    genres: ['Drama', 'Sci-Fi'],
    overview: 'Twenty years after modern civilization has been destroyed, Joel must smuggle Ellie out of an oppressive quarantine zone.',
    poster: '/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdrop: '/emttgPOgJ8ofoJjOJjNVD2qxHqo.jpg',
    network: 'HBO',
    seasons: 2,
  },
  {
    id: 84773,
    title: 'The Lord of the Rings: The Rings of Power',
    year: 2022,
    rating: 7.2,
    genres: ['Action', 'Adventure', 'Drama'],
    overview: 'Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth.',
    poster: '/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg',
    backdrop: '/aDbYlvstmI4blzi7hUc5GxSkB6u.jpg',
    network: 'Prime Video',
    seasons: 2,
  },
  {
    id: 76479,
    title: 'The Boys',
    year: 2019,
    rating: 8.5,
    genres: ['Action', 'Comedy', 'Crime'],
    overview: 'A group of vigilantes known informally as "The Boys" set out to take down corrupt superheroes with no more than blue-collar grit.',
    poster: '/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg',
    backdrop: '/mGVrXeIjyecj6TKmwPVpHlscEmw.jpg',
    network: 'Prime Video',
    seasons: 4,
  },
  {
    id: 1399,
    title: 'Game of Thrones',
    year: 2011,
    rating: 8.4,
    genres: ['Drama', 'Action', 'Fantasy'],
    overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war.',
    poster: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdrop: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    network: 'HBO',
    seasons: 8,
  },
  {
    id: 60625,
    title: 'Rick and Morty',
    year: 2013,
    rating: 8.7,
    genres: ['Animation', 'Comedy', 'Sci-Fi'],
    overview: 'Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family.',
    poster: '/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg',
    backdrop: '/45McT7kLiFLn4s4XHNqEJNrpxe6.jpg',
    network: 'Adult Swim',
    seasons: 7,
  },
];

export const POPULAR_ACTORS: Actor[] = [
  {
    id: 1,
    name: 'Cillian Murphy',
    role: 'Actor',
    photo: '/dm6V24NjjvjMiCtbMkc8Y2WPm2e.jpg',
    popularity: 98.2,
    knownFor: 'Oppenheimer',
  },
  {
    id: 2,
    name: 'Margot Robbie',
    role: 'Actress',
    photo: '/euDPyqLnuwaWMHajcU3oZ9uZezR.jpg',
    popularity: 95.7,
    knownFor: 'Barbie',
  },
  {
    id: 3,
    name: 'Ryan Gosling',
    role: 'Actor',
    photo: '/lyUyVARQKhGxaxy0FbPJCQRpiaW.jpg',
    popularity: 93.4,
    knownFor: 'La La Land',
  },
  {
    id: 4,
    name: 'Zendaya',
    role: 'Actress',
    photo: '/r3vLn1IxNNaSPi9bMJdVuEHhrEI.jpg',
    popularity: 97.1,
    knownFor: 'Dune',
  },
  {
    id: 5,
    name: 'Pedro Pascal',
    role: 'Actor',
    photo: '/9VYK7oxcqhjd5LAH6ZFJ3XzOlID.jpg',
    popularity: 91.8,
    knownFor: 'The Last of Us',
  },
  {
    id: 6,
    name: 'Florence Pugh',
    role: 'Actress',
    photo: '/6Sjz9teWjrMY9lF2o9FCo4XmoRh.jpg',
    popularity: 89.5,
    knownFor: 'Little Women',
  },
];
